[package]
name = "zkp-chaum-pedersen-gRPC"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint = { version = "0.4", features = ["rand", "serde"] }
num-traits = "0.2"
num-integer = "0.1"

rand = "0.8"
sha2 = "0.10"

serde = { version = "1.0", features = ["derive"] }